version: '3'

services:
  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    ports:
      - '8080:8080'
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
  ui:
    build: ./ui
    ports:
      - '5173:5173'
